<div class="card mb-3" style="max-width:1200px; margin: 30px auto;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="/public/picture/ceg.jpg" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-text">A Gépjárműkölcsönzés.hu, amely a világ egyik legnagyobb autókölcsönző céggé nőtte ki magát, 2022-ben alakult. A vágyunk az volt, hogy elérhető áron, ügyfélbarát minőségi szolgáltatást nyújtsunk, és ezen értékek mentén fejlesztettük hogy az egyik legjobb autóbérlési üzletággá váljon. Globális hálózatunk immár 1 országban kínál változatos szolgáltatásokat, a vevői elégedettségre és a folyamatos fejlesztésre fókuszálva, alkalmazkodva a helyi piac jellemzőihez, és kombinálva azokat a rugalmassággal, amely ahhoz szükséges, hogy lépést tartsunk az üzleti világ modernségével és innovációival.</p>
      </div>
    </div>
    <div class="col-md-8">
        <div class="card-body">
        <p class="card-text">Erőfeszítéseink eredményeként a Gépjárműkölcsönzés.hu többször elnyerte az „Év Autókölcsönzője” díjat, 2022-ben elnyerte a „Superbrands” díjat, és nemrégiben a Business Excellence Awardon a vásárlók a „Legjobb autókölcsönzőnek” választották. 2022.A Gépjárműkölcsönzés.hu, 2022-ben kezdte meg működését a magyar székhelyű Sátoraljaújhely alatt. Célunk, hogy a régóta bevált értékeket követve folytassuk működésünket, és dinamikusabban mozdítsuk elő növekedésünket és fejlődésünket, továbbra is fókuszban tartva értékes ügyfeleinket.</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src="/public/picture/dij.jpg" class="img-fluid rounded-start" alt="...">
    </div>
  </div>
  <div class="row g-0">
    <div class="col-md-4">
      <img src="/public/picture/ujauto.jpg" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-text">Szolgáltatásaink között rövid-, közép- és hosszútávú bérbeadást kínálunk magánügyfelek részére, széleskörű kiegészítő szolgáltatásokkal és folyamatosan megújuló flottával tesszük kellemessé a vezetés élményét. Hiszünk abban, hogy ügyfeleink továbbra is velünk utaznak, mert megtalálják a legjobb ár-érték arányt és a kiváló szolgáltatást a legkedvezőbb áron. Szándékunkban áll még nagyobbá és jobbá válni mindenkivel együtt, aki Magyarország legjobb autókölcsönzőjét keresi.</p>
      </div>
    </div>
</div>