
<?php if (!$params['mybookings']) : ?>
        <div class="card p-3 m-2"> 
            <div class="jumbotron text-center">
                <h2>Jelenleg nincs foglalása.</h2>
            </div>
        </div>

<?php else : ?>
   
                
    <?php foreach ($params['mybookings'] as $mybooking) : ?>

        <div class="booking_card">        
            <div class="card" style="justify-content: center;">
                        <div class="card-body">
                            <h5 class="card-title">Azonosító: <?= $mybooking['id'] ?></h5><hr>
                            <?php
                                $pdo = getConnection();
                                $statement = $pdo->prepare('SELECT * FROM `vehicles` WHERE id = ?');
                                $statement->execute([$mybooking['borrowed_vehicle_id']]);
                                $bookingvehicle = $statement->fetch(PDO::FETCH_ASSOC);
                                
                                ?>
                            <p class="card-text">Gépjármű: <?= $bookingvehicle['car'] ?></p>
                            <p class="card-text">Foglalás Kezdete: <?= $mybooking['borrow_start'] ?></p>
                            <p class="card-text">Foglalás Vége: <?= $mybooking['borrow_end'] ?></p>
                            <p class="card-text">Ár: <?= $mybooking['price'] ?> Ft</p><hr>                            
                            <span class="booking_buttons">
                            <form action="/foglalasaim?id=<?= $mybooking['id'] ?>" method="POST">
                                <button type="submit" class="btn btn-danger"><i class="bi bi-cart-x-fill"></i> Foglalás lemondása</button></span>
                            </form>
                        </div>
            </div>
        </div>


    <?php endforeach; ?>
               
        
<?php endif ?>