    <div class="single_card">
        <div class="card mb-12" style="height: 100%;" >
            <div class="row g-0">
                <div class="col-md-4">
                    <img class="img-fluid rounded-start" style="border-radius: 6px;" src="data:image/jpeg;base64,<?php echo base64_encode($params['car']['image']); ?>">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><?= $params['car']['car'] ?></h5>
                        <p class="card-header">Leírás: <?= $params['car']['info'] ?></p>


                        <p class="card-header">Napi ár: <?= $params['car']['daily_price'] ?> Ft</p>
                    </div>
                    <div class="card-text-container">
            <div class="card-booking">
            <form action="/booking?id=<?= $params['car']['id'] ?>" method="POST" class="booking_form">
                        <?php if ($params['info'] === "invaliddate") : ?>
                            <div class="alert alert-danger">
                                Mai dátumnál nem foglalhat hamarabb.
                            </div>
                        <?php endif ?>
                        <?php if ($params['info'] === "invaliddate1") : ?>
                            <div class="alert alert-danger">
                                Nem hozhatja vissza hamarabb az autót,ha még el se vitte.
                            </div>
                        <?php endif ?>
                        <?php if ($params['info'] === "invaliddriverlicense") : ?>
                            <div class="alert alert-danger">
                                Adja meg a vezetői engedély számát.
                            </div>
                        <?php endif ?>
                <div class="booking_date">
                    <label class="booking_date_label" for="booking">Bérlés kezdete:</label>
                    <input type="date" id="start_booking" name="start_booking">
                </div>    
                <div class="booking_date2">
                    <label class="booking_date_label" for="booking">Bérlés lejárata:</label>
                    <input type="date" id="end_booking" name="end_booking">
                </div>
                    <label class="w-100">
                        Vezetői engedélyszám:
                        <input class="form-control" type="text"
                            name="v_eng_szam">
                    </label>
                    <button type="submit" class="btn
                            btn-primary">Foglalás</button>

            </form>
            </div>
        </div>
    </div>
    </div>
                </div>
            </div>
