<!doctype html>
<html lang="hu">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gépjármű Kölcsönzés</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="/public/style.css">
  </head>
  <body>
    <!--NAV-->
    <nav class="navbar">
    <div class="brand-title"><img style="width: 40px;" src="/public/picture/companylogo.png" alt="cég logo"></div>
        <a href="#" class="toggle-button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </a>
        <div class="navbar-links">
            <ul>
              <li class='active'><a href='/'><span>Kezdőlap</span></a></li>
              <li class="left"><a href='#'><span>Rólunk</span></a></li>
              <li class="left"><a href='#elerhetosegek'><span>Elérhetőségek</span></a></li>
              <li class="left">
                <?php if($params['bejelentkezve']): ?>
                  <li><a href='/foglalasaim'><span>Foglalásaim</span></a></li>
                <?php endif; ?> 
            </li>
        </div>
        <div class="navbar-links2">  
            <li id="username_name">
                <?php if($params['bejelentkezve']): ?>
                  <a href='/profil?id=<?= $_SESSION['userID'] ?>'><span><?=$_SESSION['username']?></span></a>
                <?php endif; ?> 
            </li>  

            <li class="logout_button">
                <?php if($params['bejelentkezve']): ?>
                    <form action="/logout" method="POST">
                        <button type="submit" class="btn btn-sm btn-danger m-2">Kijelentkezés</button>
                    </form>
                <?php endif; ?> 
            </li>   
            </ul>
        </div>
    </nav>
    <!--NAV-->
    <main>
      <div class="container">
        <?= $params['content'] ?>
      </div>
    </main>
    <!--FOOTER-->
    <footer id="elerhetosegek">
        <div class="bg-light py-4">
            <div class="footer_container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10610.819655682133!2d21.560107!3d48.3277546!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x56ea48a5baa04ff7!2sNikoletta%20ker%C3%A1mia!5e0!3m2!1shu!2shu!4v1664444547819!5m2!1shu!2shu" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                <div class="footer_row">
                <p><strong>Cég információ:</strong></p>
                <p><img style="width: 30px;" src="/public/picture/regnum.png" alt="székhely ikon">  86 49 473538</p>
                <p><img style="width: 30px;" src="/public/picture/logo.png" alt="logo ikon">  Balogh és társai Nyrt. Személygépjármű bérlés</p>
                <p><img style="width: 30px;" src="/public/picture/location.png" alt="székhely ikon">  Sárospatak, Wesselényi út 26. 3950</p>
                <p><img style="width: 30px;" src="/public/picture/tax.png" alt="adó szám ikon">  77974667-7-25</p>
                  <p><img style="width: 30px;" src="/public/picture/gmail.png" alt="email ikon">  btgkkp@gmal.com</p>
                  <p><img style="width: 30px;" src="/public/picture/telephone.png" alt="telefon ikon">  +36 70 819 2269</p>
                <p><a href="/"><img style="width: 30px;" src="/public/picture/car.png" alt="autó ikon">  Autóink</a></p>
            </div>
            </div>
            <div class="container text-center">
              <p class="text-muted mb-0 py-2">© 2022 Bootstrapious All rights reserved.</p>
            </div>
          </div>
    </footer>
    <!--FOOTER-->
    <script src="/public/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>