<h1>cars</h1>

<div class="list-group">
    <?php foreach ($params['cars'] as $cars) : ?>
        <a href="/autok?id=<?= $cars['id'] ?>" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
            <img width="300px" height="220px" src="data:image/jpeg;base64,<?php echo base64_encode($cars["image"]); ?>">
                <h5 class="mb-1">
                    <?= $cars['car'] ?>
                </h5>
                <small>Info: <?= $cars["info"] ?> </small>
            </div>
            <small>Napi ár: <?= $cars["daily_price"] ?> </small>
        </a>
    <?php endforeach; ?>
</div>