
        <a href="#sec" id="gomb">Ajánlataink</a>    

  <?php foreach ($params['cars'] as $cars) : ?>
    <a href="/autok?id=<?= $cars['id'] ?>" id="faszeves">
    <div class="datas-container">
  <div class="kartya1" style="overflow-x:auto;" id="sec">
    <div class="keep">
                <img src="data:image/jpeg;base64,<?php echo base64_encode($cars["image"]); ?>">
                </div>
                <div class="datas">
                  <h2><?= $cars['car'] ?></h2><br>
                  <small>Leírás: <?= $cars["info"] ?> </small>
                  <hr>
                  <small>
                     <strong>Napi ár: <?= $cars["daily_price"] ?> </strong>
                  </small>
                  </div>
                  </div>
  </div>
  </a>
  <?php endforeach; ?>

