<div class="card p-3 m-2"> 
    <div class="jumbotron text-center">
        <h2>A tartalom megtekintéséhez bejelentkezés szükséges</h2>
    </div>
</div>

<?php if ($params['info'] === "regisztracioSikertelen") : ?>
    <div class="alert alert-danger">
        Regisztráció sikertelen!
    </div>
<?php endif ?>
<?php if ($params['info'] === "regisztracioSikeres") : ?>
    <div class="alert alert-success">
        Sikeres regisztráció!
    </div>
<?php endif ?>
<?php if ($params['info'] === "hibasadatok") : ?>
    <div class="alert alert-danger">
        Sikertelen bejelentkezés!
    </div>
<?php endif ?>

<?php if ($params['isRegistration']) : ?>
    <form action="/register" method="POST">
    <label class="w-100">
            Felhasználónév:
            <input class="form-control" type="text" name="username">
        </label>
        <label class="w-100">
            Keresztnév:
            <input class="form-control" type="text" name="keresztnev">
        </label>
        <label class="w-100">
            Vezeték név:
            <input class="form-control" type="text" name="vezeteknev">
        </label>
        <label class="w-100">
            Jelszó:
            <input class="form-control" type="password" name="jelszo">
        </label>
        <label class="w-100">
            Email:
            <input class="form-control" type="text" name="email">
        </label>
        <label class="w-100">
            Telefonszám:
            <input class="form-control" type="number" name="telefonszam">
        </label>
        <button type="submit" class="btn btn-success form-control">Regisztráció</button>
    </form>
    Van már felhasználói fiókod?
    <a href="<?= $params['url'] ?>">Bejelentkezés</a>

<?php else : ?>

    <form action="/login" method="POST">
        <label class="w-100">
            Felhasználónév:
            <input class="form-control" type="text" name="username">
        </label>

        <label class="w-100">
            Jelszó:
            <input class="form-control" type="password" name="password">
        </label>
        <button type="submit" class="btn btn-primary form-control">Bejelentkezés</button>
    </form>
    Nincs még felhasználói fiókod?
    <a href="<?= $params['url'] ?>&isRegistration=1">Regisztráció</a>
<?php endif ?>

