<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/bootstrap.min.css">
    <title>Gépjármű kölcsönzés</title>
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <link rel="stylesheet" href="/public/fooldalstyle.css">
</head>

<body>
    <nav>
        <div id='cssmenu'>
            <ul>
            <li class='active'><a href='/'><span>Autok</span></a></li>
            <li style="float: right;">
                <?php if($params['bejelentkezve']): ?>
                    <form action="/logout" method="POST">
                        <button type="submit" class="btn btn-sm btn-danger m-2">Kijelentkezés</button>
                    </form>
                <?php endif; ?> 
            </li>     
            </ul>
        </div>
    </nav>
    <section>
        <div id="olvasstovább">
            <img src="/public/picture/olvass.jpg" alt="Fejléc Háttér" style="width: 100%;">
        </div>
    </section>

    <?= $params['content'] ?>
    
    <script src="/public/fooldal.js"></script>
</body>

</html>